Feature/sms alert
navikt/innbyggerpanelet pull request #111
Opened 2022-06-15 08:33 UTC by perkynades

Sms messaging of invitations to insight through DittNAV kafka broker. An extra `docker-compose-sms.yaml` has been added in order to start DittNAV locally. These changes comes with an update to the .env file, contact me on slack to get the new env's.

Note: sms is sent with Altinn, so all sms will be sent between 08:00 - 16:00

What remains before this is 100% functional is the retreiving of a persons birth number, as this is used by altinn to get a persons phone number and email adress.

2022-06-17 08:32 UTC, amundlrohne requested changes
Good work! A few changes to be made, but nothing major. :)

2022-06-17 08:32 UTC, amundlrohne commented on docker-compose.yml
> +    #         - 8080:8080
Remove?

2022-06-17 08:32 UTC, amundlrohne commented on apps/api/src/routes/SmsRoutes.ts
> +});
SMS should be triggered by the MessageService to prevent spam, and unintentional triggers.

2022-06-17 08:32 UTC, amundlrohne commented on apps/frontend/src/api/hooks/useSms.ts
> +};
As mentioned in SmsRoutes and discussed in the office. I believe we should prevent SMS from being triggered through the frontend, and rather keep it backend centric.

2022-06-21 07:29 UTC, amundlrohne approved these changes
LGTM, good work! I will need the new .env fields on slack though 😅 Take a look at my comment about bulk SMS.

2022-06-21 07:29 UTC, amundlrohne commented on apps/api/src/routes/CandidateRoutes.ts
> +        });
Does this take into consideration that the CreateInsight component posts an array of candidates? Might have to implement some sort of bulk operation if not.

2022-06-21 07:29 UTC, amundlrohne commented on apps/api/src/builders/util/kafkaMessageValidation.ts
> +};
Could have used class-validator here for better consistency with the rest of the code, but this should work just fine.

2022-06-22 08:03 UTC, perkynades commented on apps/api/src/routes/CandidateRoutes.ts
> +        });
Moved it to service class, where we are sure that as each candidate get stored in the database a sms is sent

2022-06-24 12:59 UTC, merged