Insight project CRUD
navikt/innbyggerpanelet pull request #21
Opened 2022-01-06 12:26 UTC by amundlrohne

closes #4

Still misses relevancy grading as this is yet to be decided by #20

2022-01-14 10:34 UTC, perkynades requested changes
God helg :)

2022-01-14 10:34 UTC, perkynades commented on apps/api/src/main.ts
>  });
This will breake the new api structure :)

2022-01-14 10:34 UTC, perkynades commented on apps/frontend/src/app/components/project/ProjectEdit.tsx
> +            <BodyShort>TODO</BodyShort>
Write an issue on it instead of leaving it visible to the end user

2022-01-14 10:34 UTC, perkynades commented on apps/frontend/src/app/components/project/ProjectInsightEntry.tsx
> +        </div>
Split into seperate components

2022-01-14 10:34 UTC, perkynades commented on apps/frontend/src/app/components/project/ProjectOverview.tsx
> +            <BodyShort>TODO</BodyShort>
Issue :)

2022-01-14 10:34 UTC, perkynades commented on apps/frontend/src/main.tsx
> +        </BrowserRouter>
This is different from another one of your PR's

2022-01-14 10:34 UTC, perkynades commented on libs/api-interfaces/src/lib/api-interfaces.ts
> +    education:
Remember to update :)

2022-01-14 10:35 UTC, perkynades commented on apps/api/src/main.ts
>  });
I mean, it differs from the new api structure, so thing will break

2022-01-21 13:10 UTC, amundlrohne commented
Implements #25

2022-01-27 09:04 UTC, perkynades requested changes
Looks very good! Just fix the database api calls directory so that nothing breaks :)

2022-01-27 09:04 UTC, perkynades commented on apps/api/src/queries/Candidate.ts
> +
Database calls in queries folder instead of services folder

2022-01-27 09:04 UTC, perkynades commented on apps/api/src/queries/Criteria.ts
> +};
Database calls in queries folder instead of services folder

2022-01-27 09:04 UTC, perkynades commented on apps/api/src/queries/index.ts
> +export * from './Criteria';
Database calls in queries folder instead of services folder

2022-01-27 09:26 UTC, perkynades approved these changes

2022-01-27 09:26 UTC, merged