feat[frontend]: criteria admin panel
navikt/innbyggerpanelet pull request #25
Opened 2022-01-13 11:18 UTC by amundlrohne

Closes #24

2022-01-13 11:23 UTC, amundlrohne commented
Is dependent on #16

2022-01-14 10:26 UTC, perkynades requested changes
Looks very good, there are just some small things u need to change before merging :)

2022-01-14 10:26 UTC, perkynades commented on apps/frontend/src/app/containers/criteriaAdministration/CriteriaAdminPanel.tsx
> +    );
Here there is a lot happening, split it up into seperate components

2022-01-14 10:26 UTC, perkynades commented on libs/api-interfaces/src/lib/api-interfaces.ts
> +    description: string;
Remember to update these :D

2022-01-21 13:10 UTC, closed without merging